---
- name: Kubernetes-CIS-Hardening-V1
  hosts: master
  become: true
  vars:
       fix_file_permissions: "yes"
  tasks:
    - name: Ensure files do not have open permissions
      when: fix_file_permissions  | default(false)
      file:
          path: "{{ item.path }}"
          mode: "{{ item.mode }}"
          group: "{{ item.group | default( 'root' ) }}"
          owner : "{{ item.owner | default( 'root' ) }}"
          recurse: "{{ item.recurse | default( 'no' ) }}"
      with_items:
          - path: /etc/kubernetes/manifests/kube-apiserver.yaml
            mode: "0600"
          - path: /etc/kubernetes/manifests/kube-controller-manager.yaml
            mode: "0600"
          - path: /etc/kubernetes/manifests/kube-scheduler.yaml
            mode: "0600"
          - path: /etc/kubernetes/manifests/etcd.yaml
            mode: "0600"
          - path: /etc/cni/net.d
            mode: "0644"
            recurse: yes
          - path: /opt/cni/bin
            mode: "0644"
            recurse: yes
          - path: /var/lib/etcd
            mode: "0700"
            recurse: yes
          - path: /etc/kubernetes/admin.conf
            mode: "0600"
          - path: /etc/kubernetes/scheduler.conf
            mode: "0600"
          - path: /etc/kubernetes/controller-manager.conf
            mode: "0600"
          - path: /etc/kubernetes/pki/
            mode: "0755"
          - path: /etc/kubernetes/pki/apiserver-etcd-client.crt
            mode: "0644"
          - path: /etc/kubernetes/pki/apiserver-kubelet-client.crt
            mode: "0644"
          - path: /etc/kubernetes/pki/ca.crt
            mode: "0644"
          - path: /etc/kubernetes/pki/front-proxy-ca.crt
            mode: "0644"
          - path: /etc/kubernetes/pki/front-proxy-client.crt
            mode: "0644"
          - path: /etc/kubernetes/pki/apiserver-etcd-client.key
            mode: "0600"
          - path: /etc/kubernetes/pki/apiserver.key
            mode: "0600"
          - path: /etc/kubernetes/pki/apiserver-kubelet-client.key
            mode: "0600"
          - path: /etc/kubernetes/pki/ca.key
            mode: "0600"
          - path: /etc/kubernetes/pki/front-proxy-ca.key
            mode: "0600"
          - path: /etc/kubernetes/pki/front-proxy-client.key
            mode: "0600"
          - path: /etc/kubernetes/pki/sa.key
            mode: "0600"
          - path: /etc/kubernetes/pki/sa.pub
            mode: "0600"
          - path: /etc/kubernetes/pki/etcd/ca.crt
            mode: "0644"
          - path: /etc/kubernetes/pki/etcd/healthcheck-client.crt
            mode: "0644"
          - path: /etc/kubernetes/pki/etcd/peer.crt
            mode: "0644"
          - path: /etc/kubernetes/pki/etcd/server.crt
            mode: "0644"
          - path: /etc/kubernetes/pki/etcd/ca.key
            mode: "0600"
          - path: /etc/kubernetes/pki/etcd/healthcheck-client.key
            mode: "0600"
          - path: /etc/kubernetes/pki/etcd/peer.key
            mode: "0600"
          - path: /etc/kubernetes/pki/etcd/server.key
            mode: "0600"

    - name: Ensure variables are missing from kube-apiserver.yaml so we can add them later
      when: fix_k8s_components  | default(true)
      lineinfile:
          path: /etc/kubernetes/manifests/kube-apiserver.yaml
          regexp: "{{ item }}"
          state: absent
      with_items:
          - "--audit-log-path"
          - "--audit-log-maxage"
          - "--audit-log-maxbackup"
          - "--audit-log-maxsize"
          - "--authorization-mode"
          - "--insecure-port"
          - "--service-account-lookup" # Just delete this one
          - "--basic-auth-file" # Just delete this one
          - "--token-auth-file" # Just delete this one
          - "--insecure-bind-address" # Just delete this one

    - name: Add custom variables to the kube-apiserver.yaml
      when: fix_k8s_components  | default(true)
      lineinfile:
          path: "/etc/kubernetes/manifests/kube-apiserver.yaml"
          insertafter: '-\skube-apiserver'
          line: "{{ item }}"
      with_items:
          - "    - --audit-log-path=/var/log/apiserver/audit.log"
          - "    - --audit-log-maxage=30"
          - "    - --audit-log-maxbackup=5"
          - "    - --audit-log-maxsize=100"
          - "    - --authorization-mode=Node,RBAC"

    - name: Add volume mount for logs to the kube-apiserver.yaml
      when: fix_k8s_components  | default(true)
      blockinfile:
          path: "/etc/kubernetes/manifests/kube-apiserver.yaml"
          insertafter: "{{ item.insertafter }}"
          marker: "{{ item.marker }}"
          marker_begin: "BEGIN"
          marker_end: "END"
          block: "{{ item.block }}"
      with_items:
          - insertafter: 'volumes:'
            marker: "# {mark} volumes section"
            block: |2
                - hostPath:
                      path: /var/log/apiserver
                      type: DirectoryOrCreate
                  name: audit-log
          - insertafter: 'volumeMounts:'
            marker: "# {mark} volume mounts section"
            block: |4
                    - mountPath: /var/log/apiserver
                      name: audit-log

    - name: Ensure variables are missing from kube-controller-manager.yaml so we can add them later
      when: fix_k8s_components  | default(true)
      lineinfile:
          path: /etc/kubernetes/manifests/kube-controller-manager.yaml
          regexp: "{{ item }}"
          state: absent
      with_items:
          - "--terminated-pod-gc-threshold"

    - name: Add custom variables to the kube-apiserver.yaml
      when: fix_k8s_components  | default(true)
      lineinfile:
          path: "/etc/kubernetes/manifests/kube-controller-manager.yaml"
          insertafter: '-\skube-controller-manager'
          line: "{{ item }}"
      with_items:
          - "    - --terminated-pod-gc-threshold=1000"

    - name: Ensure variables are missing from kube-scheduler.yaml so we can add them later
      when: fix_k8s_components  | default(true)
      lineinfile:
          path: /etc/kubernetes/manifests/kube-scheduler.yaml
          regexp: "{{ item }}"
          state: absent
      with_items:
          - "--bind-address"

    - name: Add custom variables to the kube-scheduler.yaml
      when: fix_k8s_components  | default(true)
      lineinfile:
          path: "/etc/kubernetes/manifests/kube-scheduler.yaml"
          insertafter: '-\skube-scheduler'
          line: "{{ item }}"
      with_items:
          - "    - --bind-address=127.0.0.1"

    - name: Ensure variables are missing from etcd.yaml so we can add them later
      when: fix_k8s_components  | default(true)
      lineinfile:
          path: /etc/kubernetes/manifests/etcd.yaml
          regexp: "{{ item }}"
          state: absent
      with_items:
          - "--auto-tls"

    - name: Add custom variables to the etcd.yaml
      when: fix_k8s_components  | default(true)
      lineinfile:
          path: "/etc/kubernetes/manifests/etcd.yaml"
          insertafter: '-\setcd'
          line: "{{ item }}"
      with_items:
          - "    - --auto-tls=false"

    - name: Disable swap
      command: swapoff -a
      changed_when: false

    - name: Check if /etc/default/kubelet exists
      stat:
        path: /etc/default/kubelet
      register: kubelet_file

    - name: Create /etc/default/kubelet if it doesn't exist
      copy:
        content: |
          KUBELET_EXTRA_ARGS=--protect-kernel-defaults=true
        dest: /etc/default/kubelet
        mode: '0644'
      when: not kubelet_file.stat.exists

    - name: Set kubelet hardening options
      lineinfile:
        path: /etc/default/kubelet
        line: "{{ item }}"
        state: present
      with_items:
        - KUBELET_EXTRA_ARGS=--protect-kernel-defaults=true
      notify:
        - restart kubelet

    - name: Read kube-apiserver manifest file
      slurp:
        path: /etc/kubernetes/manifests/kube-apiserver.yaml
      register: kube_apiserver_manifest

    - name: Modify kube-apiserver manifest
      replace:
        path: /etc/kubernetes/manifests/kube-apiserver.yaml
        regexp: '^(.*--anonymous-auth=)(true)(.*)$'
        replace: '\1false\3'
      when: "'--anonymous-auth=false' not in kube_apiserver_manifest.content | b64decode"

    - name: Restart kubelet
      service:
        name: kubelet
        state: restarted
    - name: Read kube-apiserver manifest file
      slurp:
        path: /etc/kubernetes/manifests/kube-apiserver.yaml
      register: kube_apiserver_manifest

    - name: Modify kube-apiserver manifest
      replace:
        path: /etc/kubernetes/manifests/kube-apiserver.yaml
        regexp: '^.*(--token-auth-file=).*$'
        replace: ''
      when: "'--token-auth-file=' in kube_apiserver_manifest.content | b64decode"

    - name: Restart kubelet
      service:
        name: kubelet
        state: restarted


- name: Remove DenyServiceExternalIPs parameter from kube-apiserver manifest
  hosts: master
  become: true
  tasks:
    - name: Read kube-apiserver manifest file
      slurp:
        path: /etc/kubernetes/manifests/kube-apiserver.yaml
      register: kube_apiserver_manifest

    - name: Modify kube-apiserver manifest
      replace:
        path: /etc/kubernetes/manifests/kube-apiserver.yaml
        regexp: '^.*(--DenyServiceExternalIPs).*$'
        replace: ''
      when: "'--DenyServiceExternalIPs' in kube_apiserver_manifest.content | b64decode"

    - name: Modify kube-apiserver manifest with disable-admission-plugins
      replace:
        path: /etc/kubernetes/manifests/kube-apiserver.yaml
        regexp: '^.*(--disable-admission-plugins=).*$'
        replace: '\1DenyServiceExternalIPs'
      when: "'--disable-admission-plugins=DenyServiceExternalIPs' not in kube_apiserver_manifest.content | b64decode"

    - name: Restart kubelet
      service:
        name: kubelet
        state: restarted

- name: Ensure that the admission control plugin AlwaysAdmit is not set
  hosts: master
  become: true
  tasks:
    - name: Read kube-apiserver manifest file
      slurp:
        path: /etc/kubernetes/manifests/kube-apiserver.yaml
      register: kube_apiserver_manifest

    - name: Modify kube-apiserver manifest to remove or change --enable-admission-plugins
      replace:
        path: /etc/kubernetes/manifests/kube-apiserver.yaml
        regexp: '^.*(--enable-admission-plugins=).*$'
        replace: ''
      when: "'--enable-admission-plugins' in kube_apiserver_manifest.content | b64decode or 'AlwaysAdmit' in kube_apiserver_manifest.content | b64decode"

- name: Ensure that the admission control plugin AlwaysPullImages,NodeRestriction,SecurityContextDeny,NodeRestriction is set
  hosts: master
  become: true
  tasks:
    - name: Read kube-apiserver manifest file
      slurp:
        path: /etc/kubernetes/manifests/kube-apiserver.yaml
      register: kube_apiserver_manifest

    - name: Modify kube-apiserver manifest to add --enable-admission-plugins
      lineinfile:
        path: /etc/kubernetes/manifests/kube-apiserver.yaml
        line: "    - --enable-admission-plugins=AlwaysPullImages,NodeRestriction,SecurityContextDeny,NodeRestriction"
        insertafter: '^(\s*)- --authorization-mode=Node,RBAC'
      when: "'--enable-admission-plugins=' not in kube_apiserver_manifest.content | b64decode"

    - name: Restart kubelet
      service:
        name: kubelet
        state: restarted

- name: Ensure that the --terminated-pod-gc-threshold argument is set as appropriate
  hosts: master
  become: true
  tasks:
    - name: Read kube-controller-manager manifest file
      slurp:
        path: /etc/kubernetes/manifests/kube-controller-manager.yaml
      register: kube_controller_manager_manifest

    - name: Modify kube-controller-manager manifest
      replace:
        path: /etc/kubernetes/manifests/kube-controller-manager.yaml
        regexp: '(- --terminated-pod-gc-threshold=).*'
        replace: '\g<1>10'
      when: "'- --terminated-pod-gc-threshold=' in kube_controller_manager_manifest.content | b64decode"

- name: Ensure that the RotateKubeletServerCertificate argument is set to true
  hosts: master
  become: true

  tasks:
    - name: Read kube-controller-manager manifest file
      slurp:
        path: /etc/kubernetes/manifests/kube-controller-manager.yaml
      register: kube_controller_manager_manifest

    - name: Modify kube-controller-manager manifest
      lineinfile:
        path: /etc/kubernetes/manifests/kube-controller-manager.yaml
        regexp: '^\s*- --use-service-account-credentials=true$'
        insertafter: '^\s*- --use-service-account-credentials=true$'
        line: '    - --feature-gates=RotateKubeletServerCertificate=true'
      when: "'--feature-gates=RotateKubeletServerCertificate=true' not in kube_controller_manager_manifest.content | b64decode"

    - name: Restart kubelet
      service:
        name: kubelet
        state: restarted

- name: Ensure that the kubelet service file permissions are set to 600 or more restrictive
  hosts: all
  become: true
  tasks:
    - name: Change file permission 10-kubeadm.conf
      file:
        path: /usr/lib/systemd/system/kubelet.service.d/10-kubeadm.conf
        mode: "0600"
        owner: root
        group: root
    - name: Change file permission kubelet/config.yaml
      file:
        path: /var/lib/kubelet/config.yaml
        mode: "0600"
        owner: root
        group: root

