apiVersion: v1
kind: ConfigMap
metadata:
  name: pod-security-config
  namespace: kube-system
data:
  pod-security-policy.yaml: |
    apiVersion: policy/v1beta1
    kind: PodSecurityPolicy
    metadata:
      name: restrict-static-pods
    spec:
      privileged: false
      allowPrivilegeEscalation: false
      requiredDropCapabilities:
        - ALL
      hostNetwork: false
      hostIPC: false
      hostPID: false
      runAsUser:
        rule: 'RunAsAny'
      seLinux:
        rule: 'RunAsAny'
      supplementalGroups:
        rule: 'MustRunAs'
        ranges:
          - min: 1
            max: 65535
      fsGroup:
        rule: 'MustRunAs'
        ranges:
          - min: 1
            max: 65535
      volumes:
        - 'configMap'
        - 'downwardAPI'
        - 'emptyDir'
        - 'projected'
        - 'secret'
        - 'serviceAccount'
        - 'persistentVolumeClaim'
    ---
    apiVersion: admissionregistration.k8s.io/v1beta1
    kind: ValidatingWebhookConfiguration
    metadata:
      name: restrict-static-pods
    webhooks:
      - name: restrict-static-pods.admission.k8s.io
        namespaceSelector:
          matchExpressions:
            - key: admission.kubernetes.io/default
              operator: NotIn
              values:
                - kube-system
        rules:
          - operations:
              - CREATE
            apiGroups:
              - ''
            apiVersions:
              - v1
            resources:
              - pods/static
        failurePolicy: Fail
        sideEffects: None
        admissionReviewVersions: ['v1', 'v1beta1']
        clientConfig:
          service:
            namespace: kube-system
            name: pod-security-admission-controller
            path: /validate-pod
            port: 443
          caBundle: /etc/kubernetes/pki/ca/crt